config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'users/account', to: 'users/registrations#show', as: :user_account
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: redirect('home')

  get    'home', to: 'products#home', as: 'home'
  get    'products', to: 'products#index', as: 'products'
  get    'products/:id', to: 'products#show', as: 'product'
  get    'products/:id/edit', to: 'products#edit', as: 'edit_product'
  patch  'products/:id', to: 'products#update'
  get    'order', to: 'orders#show', as: 'order'
  get    'orders', to: 'orders#index', as: 'past_orders'
  get    'confirmation/:confirmation_num', to: 'orders#confirmation', as: 'confirmation'
  post   'products/:product_id/order_items', to: 'order_items#create', as: 'add_to_cart'
  delete 'order_items/:id', to: 'order_items#destroy', as: 'order_item'
  get    'edit_payment', to: 'payments#edit', as: 'edit_payment'
  patch  'updated_payment', to: 'payments#update', as: 'updated_payment'
  get    'checkout', to: 'payments#checkout', as: 'checkout'
  patch  'complete_order', to: 'payments#complete_order', as: 'complete_order'
  get    'purchased_products/:product_id', to: 'purchased_products#show', as: 'purchased_product'
  get    'purchased_products/:product_id/new', to: 'purchased_products#new', as: 'new_purchased_product'
  post   'purchased_products/:product_id', to: 'purchased_products#create'
  get    'products/:id/leave_a_review', to: 'products#leave_review', as: 'leave_review'
end

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= alert_class(key) %> alert-dismissible fade show" role="alert">
    <div class="text-center alert-message"><%= message %></div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark custom-navbar">
  <div class="container-fluid">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
      <%= image_tag "logo.png", alt: "901 Fit Hub", class: "d-inline-block align-text-top" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    

    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Left-Aligned -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Products', products_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Shopping Cart', order_path, class: 'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My Past Orders', past_orders_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>

      <!-- Right-Aligned -->
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Hi, #{current_user.username}", user_account_path,
                        class: "nav-link #{active_class(edit_user_registration_path)} btn btn-link" %>
          </li>
          <li class="nav-item">
            <%= button_to 'Sign Out', destroy_user_session_path,
                        method: :delete, data: { turbo: false }, class: 'nav-link btn btn-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path,
                        class: "nav-link #{active_class(new_user_session_path)} btn btn-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Create Account', new_user_registration_path,
                        class: "nav-link #{active_class(new_user_registration_path)} btn btn-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>