config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'users/account', to: 'users/registrations#show', as: :user_account
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: redirect('home')

  get    'home', to: 'products#home', as: 'home'
  get    'products', to: 'products#index', as: 'products'
  get    'products/:id', to: 'products#show', as: 'product'
  get    'products/:id/edit', to: 'products#edit', as: 'edit_product'
  patch  'products/:id', to: 'products#update'
  get    'order', to: 'orders#show', as: 'order'
  get    'orders', to: 'orders#index', as: 'past_orders'
  get    'confirmation/:confirmation_num', to: 'orders#confirmation', as: 'confirmation'
  post   'products/:product_id/order_items', to: 'order_items#create', as: 'add_to_cart'
  delete 'order_items/:id', to: 'order_items#destroy', as: 'order_item'
  get    'edit_payment', to: 'payments#edit', as: 'edit_payment'
  patch  'updated_payment', to: 'payments#update', as: 'updated_payment'
  get    'checkout', to: 'payments#checkout', as: 'checkout'
  patch  'complete_order', to: 'payments#complete_order', as: 'complete_order'
  get    'purchased_products/:product_id', to: 'purchased_products#show', as: 'purchased_product'
  get    'purchased_products/:product_id/new', to: 'purchased_products#new', as: 'new_purchased_product'
  post   'purchased_products/:product_id', to: 'purchased_products#create'
  get    'products/:id/leave_a_review', to: 'products#leave_review', as: 'leave_review'
end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id               :bigint           not null, primary key
#  card_number      :string
#  expiration_month :integer
#  expiration_year  :integer
#  name             :string
#  security_code    :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :bigint
#
# Indexes
#
#  index_payments_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Payment < ApplicationRecord

  validates :card_number, presence: true, format: { with: /\A\d+\z/ }, length: { is: 16 }
  validates :security_code, presence: true, format: { with: /\A\d+\z/ }, length: { in: 3..4 }
  validates :name, presence: true
  validates :expiration_month, presence: true, inclusion: { in: 1..12 }
  validates :expiration_year, presence: true

  validate :expiration_date_not_expired

  belongs_to :user

  def expiration_date_not_expired
    card_exp = Date.new(expiration_year, expiration_month).end_of_month
    today = Date.today
    if card_exp < Date.today.end_of_month
      errors.add(:base, "Your card's expiration date has passed")
    end
  end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController < ApplicationController
  before_action :authenticate_user!

  def checkout
    @order = current_user.orders.find_by(status: :cart)

    if @order.order_items.empty?
      flash[:error] = 'Must have items in your cart before purchasing'
      redirect_to products_path
    else
      @payment = current_user.payment
      render :checkout
    end
  end

  def edit
    @payment = current_user.payment
    render :edit_payment
  end

  def update
    @payment = current_user.payment
    if @payment.update(params.require(:payment).permit(:name, :card_number, :expiration_month, :expiration_year,
                                                       :security_code))
      flash[:success] = 'Your information was successfully updated!'
      redirect_to user_account_path
    else
      flash.now[:error] = @payment.errors.objects.first.full_message
      render :edit_payment
    end
  end

  def complete_order
    @payment = current_user.payment
    if @payment.update(params.require(:payment).permit(:name, :card_number, :expiration_month, :expiration_year,
                                                       :security_code))
      @order = current_user.orders.find_by(status: :cart)
      @order.update(status: :completed)
      @order.order_items.each do |order_item|
        product = order_item.product
        unless current_user.purchased_products.exists?(product: product)
          reviewable_product = current_user.purchased_products.create!(
            product: product,
            review_title: "Pending Review",
            review_rating: 0,
            review_recommendation: nil,
            review_description: nil
          )
        end
      end

      current_user.orders.create!(status: :cart)
      flash[:success] = 'Your purchase was successful!'

      redirect_to confirmation_path(confirmation_num: @order.confirmation_number)

    else
      flash.now[:error] = @payment.errors.objects.first.full_message
      render :checkout
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/checkout.html.erb
<h1>Enter Payment Information</h1>

<%= bootstrap_form_with model: @payment, url: complete_order_path, method: :patch, local: true, data: { turbo: false } do |f| %>
    <%= f.text_field :name %>
    <%= f.text_field :card_number %>
    <%= f.select :expiration_month, [["January", 1], ["February", 2], ["March", 3], ["April", 4], ["May", 5], ["June", 6], ["July", 7], ["August", 8], ["September", 9], ["October", 10], ["November", 11], ["December", 12]]%>
    <%= f.select :expiration_year, (2024..2033).to_a%>
    <%= f.text_field :security_code %>
    <%= f.submit "Complete Order", class: 'btn btn-primary' %>

<% end %>

app/views/payments/edit_payment.html.erb
<h1>Edit Payment Information</h1>

<%= bootstrap_form_with model: @payment, url: updated_payment_path, method: :patch, local: true, data: { turbo: false } do |f| %>
    <%= f.text_field :name %>
    <%= f.text_field :card_number %>
    <%= f.select :expiration_month, [["January", 1], ["February", 2], ["March", 3], ["April", 4], ["May", 5], ["June", 6], ["July", 7], ["August", 8], ["September", 9], ["October", 10], ["November", 11], ["December", 12]]%>
    <%= f.select :expiration_year, (2024..2033).to_a%>
    <%= f.text_field :security_code %>
    <%= f.submit "Update Info", class: 'btn btn-primary' %>

<% end %>